# Generated by Django 5.2.6 on 2025-11-26 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('head', 'Cabeça/Acessórios'), ('top', 'Tronco'), ('bottom', 'Pernas'), ('feet', 'Pés')], max_length=10)),
                ('size', models.CharField(blank=True, max_length=10, null=True)),
                ('color', models.CharField(default='#000000', max_length=7)),
                ('image', models.ImageField(upload_to='closet_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothing_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
