# Generated by Django 5.2.6 on 2025-11-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='subcategory',
            field=models.CharField(choices=[('cap', 'Boné'), ('hat', 'Chapéu'), ('beanie', 'Gorro'), ('glasses', 'Óculos'), ('t-shirt', 'Camiseta'), ('shirt', 'Camisa Social'), ('sweatshirt', 'Moletom/Suéter'), ('jacket', 'Jaqueta/Casaco'), ('blouse', 'Blusa'), ('dress', 'Vestido'), ('pants', 'Calça'), ('shorts', 'Shorts/Bermuda'), ('skirt', 'Saia'), ('sneakers', 'Tênis'), ('boots', 'Bota'), ('shoes', 'Sapato Social'), ('sandals', 'Sandália'), ('other', 'Outro')], default='other', max_length=20),
        ),
    ]
